[package]
name = "aarch64"
version = "0.1.0"
authors = ["vibhoothi <vibhoothiiaanand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0"
